-d C:\Users\Ahmet\Documents\traffic_light\impl\gwsynthesis\traffic_light.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst C:\Users\Ahmet\Documents\traffic_light\src\traffic_light.cst
-cfg C:\Users\Ahmet\Documents\traffic_light\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 10
