-d C:\Users\Ahmet\Desktop\gowin_odev\Turnike\impl\gwsynthesis\Turnike.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst C:\Users\Ahmet\Desktop\gowin_odev\Turnike\src\Turnike.cst
-cfg C:\Users\Ahmet\Desktop\gowin_odev\Turnike\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 10
